@echo off
echo Starting WeezGen with Socket.io...
echo.
echo Starting Socket.io server on port 3001...
start "Socket.io Server" cmd /k "node socket-server.js"
echo.
echo Starting Next.js development server on port 3000...
start "Next.js Dev Server" cmd /k "npm run dev"
echo.
echo Both servers are starting...
echo Socket.io server: http://localhost:3001
echo Next.js app: http://localhost:3000
echo.
echo Press any key to close this window...
pause > nul
